[features]
seeds = false
[programs.devnet]
myproject = "Hy24t9n3aQXfyr5Lc8KFFBoCEAGbEe2K1M64EnoXTaQZ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/mattmasteller/.config/solana/id.json"

[scripts]
test = "node tests/myproject.js"
